name: ClansPro
author: FahmiCyber
description: A Plugin For Easily Managing Factions
version: 7.0
main: ClansPro\ClanMain
api: 
 - 1.12.0
 - 2.0.0
commands:
  clan:
    description: use /clan help for all parameters
    permission: clan.command
permissions:
  clan.command:
    default: true
